### ISSUE TITLE
Build error with GCC10

### ISSUE THREAD

**Issue by boredness** [myrsloik/VapourSynth-FFT3DFilter#11]
Build log: https://0x0.st/iWTj.log

`meson build
ninja -C build/`

% gcc --version                                                                        
gcc (GCC) 10.1.0
OS: Arch

**Comment by myrsloik** [comment]
"#include \<stdexcept\>" and try again

**Comment by LaserEyess** [comment]
~~`#include` what? I'm not a C++ programmer I don't know what header provides `runtime_error`.~~

Decided to git gud and google it. `#include <stdexcept>` in `FFT3DFilter.cpp` and `Plugin.cpp` worked.

**Comment by myrsloik** [comment]
Fixed in the source tree now
