### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by myrsloik** [myrsloik/VapourSynth-FFT3DFilter#3]
The documentation wasn't converted to something more modern than 90s html style. The original official docs also seem to be missing a lot of hints about what's sane to do.

**Comment by 4re** [comment]
If you are OK with a typical markdown page I can do it.
EDIT: original documentation looks like a pain in the ass. :/

**Comment by myrsloik** [comment]
Yes, markdown is the bestest. I guess. I don't like the original documentation either, it's confusing, long and kinda wrong.

**Comment by vsfanatic** [comment]
Here's a [proposed doc](https://gist.github.com/vsfanatic/8b5c1ed868e19f84a15cbe25b5d851b9#file-fft3dfilter_readme-md)

Feel free to modify, reduce, whatever you find necessary.

**Comment by myrsloik** [comment]
Nice, sigma values aren't scaled so they need to be scaled with input depth. Definitely should be noted. Float needs like /256 scaling and 16 bit *256 (approximately) for similar results.

You don't mention the very important pframe argument in the noise pattern/pfactor section. That should also be note I guess. Change that and I'll steal it all immediately

**Comment by vsfanatic** [comment]
Thanks. I made clearer in the readme the use of the ``pframe`` parameter.

About the scaling of sigmas and smin/smax, I didn't include any comment on the doc for this, in the hope you could include the scaling internally in the filter: **I have successfully tested the following scaling in my vpy scripts to obtain _very similar_ results with 8, 10 and 16 bit-depths**:
```python
bits = clip.format.bits_per_sample - 8
sigma_f = 1<<bits
s1 = 6.0  * sigma_f
s2 = 0.75 * sigma_f
s3 = 0.75 * sigma_f
s4 = 1.0  * sigma_f
sh_min =  4.0 * sigma_f
sh_max = 20.0 * sigma_f
ret = core.fft3dfilter.FFT3DFilter(clip=clip, sigma=s1, sigma2=s2, sigma3=s3, sigma4=s4, sharpen=0.5, dehalo=0.0, smin=sh_min, smax=sh_max)
```
Every time I use the filter. It's kinda boring.

**I haven't tried with float clips yet**, but you made me wonder, so I browsed the latest avisynth version: it does the scaling internally. [It uses 1/255](https://github.com/pinterf/fft3dfilter/blob/1b2b37ea38b6930ca360faddbc399f87178bbe6e/fft3dfilter/FFT3DFilter.cpp#L584) for floats

**Comment by vsfanatic** [comment]
Updated: (2018-03-14)
* **Included the note on the need to scale some parameters according to bit-depth**
* Gave an example of the workaround to make the pattern block coincide for luma and chroma planes when there’s chroma subsampling
* Some cosmetics

**Comment by myrsloik** [comment]
Added docs by vsfanatic
